#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v3
# autospec commit: c1050fe
#
Name     : gpredict
Version  : 2.2.1
Release  : 28
URL      : https://github.com/csete/gpredict/releases/download/v2.2.1/gpredict-2.2.1.tar.bz2
Source0  : https://github.com/csete/gpredict/releases/download/v2.2.1/gpredict-2.2.1.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: gpredict-bin = %{version}-%{release}
Requires: gpredict-data = %{version}-%{release}
Requires: gpredict-license = %{version}-%{release}
Requires: gpredict-locales = %{version}-%{release}
Requires: gpredict-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : curl-dev
BuildRequires : gettext
BuildRequires : glib-dev
BuildRequires : goocanvas-dev
BuildRequires : gtk3-dev
BuildRequires : intltool
BuildRequires : intltool-dev
BuildRequires : perl(XML::Parser)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Add-typdef-to-qth_data_type.patch
Patch2: 0002-Require-Glib-2.40-or-later.patch
Patch3: 0003-Use-PKG_CONFIG-instead-of-pkg-config-to-allow-cross-.patch
Patch4: 0004-Add-support-for-GooCanvas-3.patch

%description
Gpredict is a real time satellite tracking and orbit prediction program
for the Linux desktop. It uses the SGP4/SDP4 propagation algorithms together
with NORAD two-line element sets (TLE).

%package bin
Summary: bin components for the gpredict package.
Group: Binaries
Requires: gpredict-data = %{version}-%{release}
Requires: gpredict-license = %{version}-%{release}

%description bin
bin components for the gpredict package.


%package data
Summary: data components for the gpredict package.
Group: Data

%description data
data components for the gpredict package.


%package license
Summary: license components for the gpredict package.
Group: Default

%description license
license components for the gpredict package.


%package locales
Summary: locales components for the gpredict package.
Group: Default

%description locales
locales components for the gpredict package.


%package man
Summary: man components for the gpredict package.
Group: Default

%description man
man components for the gpredict package.


%prep
%setup -q -n gpredict-2.2.1
cd %{_builddir}/gpredict-2.2.1
%patch -P 1 -p1
%patch -P 2 -p1
%patch -P 3 -p1
%patch -P 4 -p1
pushd ..
cp -a gpredict-2.2.1 buildavx2
popd
pushd ..
cp -a gpredict-2.2.1 buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1701962410
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%reconfigure --disable-static
make  %{?_smp_mflags}
unset PKG_CONFIG_PATH
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -m64 -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -m64 -march=x86-64-v3 "
%reconfigure --disable-static
make  %{?_smp_mflags}
popd
unset PKG_CONFIG_PATH
pushd ../buildavx512/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -m64 -march=x86-64-v4 -mprefer-vector-width=512 -Wl,-z,x86-64-v4 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -m64 -march=x86-64-v4 -mprefer-vector-width=512 -Wl,-z,x86-64-v4 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -m64 -march=x86-64-v4 -mprefer-vector-width=512 -Wl,-z,x86-64-v4 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -m64 -march=x86-64-v4 -mprefer-vector-width=256 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -m64 -march=x86-64-v4 "
%reconfigure --disable-static
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :
cd ../buildavx2;
make %{?_smp_mflags} check || : || :
cd ../buildavx512;
make %{?_smp_mflags} check || : || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1701962410
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gpredict
cp %{_builddir}/gpredict-%{version}/COPYING %{buildroot}/usr/share/package-licenses/gpredict/9a13113b89f7985efe22a28b8e4ad1ace7f2b5d1 || :
pushd ../buildavx2/
%make_install_v3
popd
pushd ../buildavx512/
%make_install_v4
popd
%make_install
%find_lang gpredict
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/gpredict
/V4/usr/bin/gpredict
/usr/bin/gpredict

%files data
%defattr(-,root,root,-)
/usr/share/applications/gpredict.desktop
/usr/share/gpredict/AUTHORS
/usr/share/gpredict/COPYING
/usr/share/gpredict/NEWS
/usr/share/gpredict/README
/usr/share/gpredict/data/Amateur.mod
/usr/share/gpredict/data/locations.dat
/usr/share/gpredict/data/sample.qth
/usr/share/gpredict/data/satdata/amateur.cat
/usr/share/gpredict/data/satdata/cubesat.cat
/usr/share/gpredict/data/satdata/galileo.cat
/usr/share/gpredict/data/satdata/glo-ops.cat
/usr/share/gpredict/data/satdata/gps-ops.cat
/usr/share/gpredict/data/satdata/iridium-NEXT.cat
/usr/share/gpredict/data/satdata/iridium.cat
/usr/share/gpredict/data/satdata/molniya.cat
/usr/share/gpredict/data/satdata/noaa.cat
/usr/share/gpredict/data/satdata/satellites.dat
/usr/share/gpredict/data/satdata/science.cat
/usr/share/gpredict/data/satdata/visual.cat
/usr/share/gpredict/data/satdata/weather.cat
/usr/share/pixmaps/gpredict-icon.png
/usr/share/pixmaps/gpredict/icons/gpredict-antenna-small.png
/usr/share/pixmaps/gpredict/icons/gpredict-antenna.png
/usr/share/pixmaps/gpredict/icons/gpredict-azel-small.png
/usr/share/pixmaps/gpredict/icons/gpredict-calendar.png
/usr/share/pixmaps/gpredict/icons/gpredict-clock-small.png
/usr/share/pixmaps/gpredict/icons/gpredict-clock.png
/usr/share/pixmaps/gpredict/icons/gpredict-crash.png
/usr/share/pixmaps/gpredict/icons/gpredict-icon.png
/usr/share/pixmaps/gpredict/icons/gpredict-layout-00.png
/usr/share/pixmaps/gpredict/icons/gpredict-layout-01.png
/usr/share/pixmaps/gpredict/icons/gpredict-layout-02.png
/usr/share/pixmaps/gpredict/icons/gpredict-layout-03.png
/usr/share/pixmaps/gpredict/icons/gpredict-layout-04.png
/usr/share/pixmaps/gpredict/icons/gpredict-layout-05.png
/usr/share/pixmaps/gpredict/icons/gpredict-layout-06.png
/usr/share/pixmaps/gpredict/icons/gpredict-layout-07.png
/usr/share/pixmaps/gpredict/icons/gpredict-layout-08.png
/usr/share/pixmaps/gpredict/icons/gpredict-layout-99.png
/usr/share/pixmaps/gpredict/icons/gpredict-leds.png
/usr/share/pixmaps/gpredict/icons/gpredict-mod-attach.png
/usr/share/pixmaps/gpredict/icons/gpredict-mod-close.png
/usr/share/pixmaps/gpredict/icons/gpredict-mod-config.png
/usr/share/pixmaps/gpredict/icons/gpredict-mod-detach.png
/usr/share/pixmaps/gpredict/icons/gpredict-mod-popup.png
/usr/share/pixmaps/gpredict/icons/gpredict-notebook.png
/usr/share/pixmaps/gpredict/icons/gpredict-oscilloscope-small.png
/usr/share/pixmaps/gpredict/icons/gpredict-oscilloscope.png
/usr/share/pixmaps/gpredict/icons/gpredict-planner-small.png
/usr/share/pixmaps/gpredict/icons/gpredict-planner.png
/usr/share/pixmaps/gpredict/icons/gpredict-polar-small.png
/usr/share/pixmaps/gpredict/icons/gpredict-sat-list.png
/usr/share/pixmaps/gpredict/icons/gpredict-sat-pref.png
/usr/share/pixmaps/gpredict/icons/gpredict-shuttle-small.png
/usr/share/pixmaps/gpredict/icons/gpredict-shuttle.png
/usr/share/pixmaps/gpredict/logos/gpredict_horizontal_color.png
/usr/share/pixmaps/gpredict/logos/gpredict_horizontal_color.svg
/usr/share/pixmaps/gpredict/logos/gpredict_horizontal_white.png
/usr/share/pixmaps/gpredict/logos/gpredict_horizontal_white.svg
/usr/share/pixmaps/gpredict/logos/gpredict_icon_color.png
/usr/share/pixmaps/gpredict/logos/gpredict_icon_color.svg
/usr/share/pixmaps/gpredict/logos/gpredict_icon_white.png
/usr/share/pixmaps/gpredict/logos/gpredict_icon_white.svg
/usr/share/pixmaps/gpredict/logos/gpredict_vertical_color.png
/usr/share/pixmaps/gpredict/logos/gpredict_vertical_color.svg
/usr/share/pixmaps/gpredict/logos/gpredict_vertical_white.png
/usr/share/pixmaps/gpredict/logos/gpredict_vertical_white.svg
/usr/share/pixmaps/gpredict/maps/earth_800.png
/usr/share/pixmaps/gpredict/maps/nasa-bmng-01_1024.jpg
/usr/share/pixmaps/gpredict/maps/nasa-bmng-01_2048.jpg
/usr/share/pixmaps/gpredict/maps/nasa-bmng-03_1024.jpg
/usr/share/pixmaps/gpredict/maps/nasa-bmng-03_2048.jpg
/usr/share/pixmaps/gpredict/maps/nasa-bmng-05_1024.jpg
/usr/share/pixmaps/gpredict/maps/nasa-bmng-05_2048.jpg
/usr/share/pixmaps/gpredict/maps/nasa-bmng-07_1024.jpg
/usr/share/pixmaps/gpredict/maps/nasa-bmng-07_2048.jpg
/usr/share/pixmaps/gpredict/maps/nasa-bmng-08_1024.jpg
/usr/share/pixmaps/gpredict/maps/nasa-bmng-08_2048.jpg
/usr/share/pixmaps/gpredict/maps/nasa-topo_1024.jpg
/usr/share/pixmaps/gpredict/maps/nasa-topo_1600.jpg
/usr/share/pixmaps/gpredict/maps/nasa-topo_2048.jpg
/usr/share/pixmaps/gpredict/maps/nasa-topo_800.png

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gpredict/9a13113b89f7985efe22a28b8e4ad1ace7f2b5d1

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/gpredict.1

%files locales -f gpredict.lang
%defattr(-,root,root,-)

