#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gpredict
Version  : 1.3
Release  : 1
URL      : https://github.com/csete/gpredict/archive/v1.3.tar.gz
Source0  : https://github.com/csete/gpredict/archive/v1.3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: gpredict-bin
Requires: gpredict-data
Requires: gpredict-locales
Requires: gpredict-doc
BuildRequires : gettext
BuildRequires : glib-dev
BuildRequires : gtk+-dev
BuildRequires : intltool
BuildRequires : intltool-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(goocanvas)
BuildRequires : pkgconfig(hamlib)
BuildRequires : pkgconfig(libcurl)
Patch1: POTFILES.patch

%description
WHAT IS GPREDICT?
=================
Gpredict is a real time satellite tracking and orbit prediction program
written using the Gtk+ widgets. Gpredict is targetted mainly towards ham radio
operators but others interested in satellite tracking may find it useful as
well. Gpredict uses the SGP4/SDP4 algorithms, which are compatible with the
NORAD Keplerian elements.

%package bin
Summary: bin components for the gpredict package.
Group: Binaries
Requires: gpredict-data

%description bin
bin components for the gpredict package.


%package data
Summary: data components for the gpredict package.
Group: Data

%description data
data components for the gpredict package.


%package doc
Summary: doc components for the gpredict package.
Group: Documentation

%description doc
doc components for the gpredict package.


%package locales
Summary: locales components for the gpredict package.
Group: Default

%description locales
locales components for the gpredict package.


%prep
%setup -q -n gpredict-1.3
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1507595055
%autogen --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1507595055
rm -rf %{buildroot}
%make_install
%find_lang gpredict

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gpredict

%files data
%defattr(-,root,root,-)
/usr/share/applications/gpredict.desktop
/usr/share/gpredict/AUTHORS
/usr/share/gpredict/COPYING
/usr/share/gpredict/ChangeLog
/usr/share/gpredict/NEWS
/usr/share/gpredict/README
/usr/share/gpredict/TODO
/usr/share/gpredict/data/Amateur.mod
/usr/share/gpredict/data/locations.dat
/usr/share/gpredict/data/sample.qth
/usr/share/gpredict/data/satdata/amateur.cat
/usr/share/gpredict/data/satdata/cubesat.cat
/usr/share/gpredict/data/satdata/dmc.cat
/usr/share/gpredict/data/satdata/education.cat
/usr/share/gpredict/data/satdata/engineering.cat
/usr/share/gpredict/data/satdata/galileo.cat
/usr/share/gpredict/data/satdata/geo.cat
/usr/share/gpredict/data/satdata/geodetic.cat
/usr/share/gpredict/data/satdata/glo-ops.cat
/usr/share/gpredict/data/satdata/globalstar.cat
/usr/share/gpredict/data/satdata/goes.cat
/usr/share/gpredict/data/satdata/gorizont.cat
/usr/share/gpredict/data/satdata/gps-ops.cat
/usr/share/gpredict/data/satdata/intelsat.cat
/usr/share/gpredict/data/satdata/iridium.cat
/usr/share/gpredict/data/satdata/military.cat
/usr/share/gpredict/data/satdata/molniya.cat
/usr/share/gpredict/data/satdata/musson.cat
/usr/share/gpredict/data/satdata/nnss.cat
/usr/share/gpredict/data/satdata/noaa.cat
/usr/share/gpredict/data/satdata/orbcomm.cat
/usr/share/gpredict/data/satdata/other-comm.cat
/usr/share/gpredict/data/satdata/other.cat
/usr/share/gpredict/data/satdata/radar.cat
/usr/share/gpredict/data/satdata/raduga.cat
/usr/share/gpredict/data/satdata/resource.cat
/usr/share/gpredict/data/satdata/sarsat.cat
/usr/share/gpredict/data/satdata/satellites.dat
/usr/share/gpredict/data/satdata/sbas.cat
/usr/share/gpredict/data/satdata/science.cat
/usr/share/gpredict/data/satdata/tdrss.cat
/usr/share/gpredict/data/satdata/tle-new.cat
/usr/share/gpredict/data/satdata/visual.cat
/usr/share/gpredict/data/satdata/weather.cat
/usr/share/gpredict/data/satdata/x-comm.cat
/usr/share/gpredict/data/trsp/20439.trsp
/usr/share/gpredict/data/trsp/20442.trsp
/usr/share/gpredict/data/trsp/22825.trsp
/usr/share/gpredict/data/trsp/22826.trsp
/usr/share/gpredict/data/trsp/23439.trsp
/usr/share/gpredict/data/trsp/24278.trsp
/usr/share/gpredict/data/trsp/24786.trsp
/usr/share/gpredict/data/trsp/25338.trsp
/usr/share/gpredict/data/trsp/25397.trsp
/usr/share/gpredict/data/trsp/25544.trsp
/usr/share/gpredict/data/trsp/26352.trsp
/usr/share/gpredict/data/trsp/26536.trsp
/usr/share/gpredict/data/trsp/26871.trsp
/usr/share/gpredict/data/trsp/26931.trsp
/usr/share/gpredict/data/trsp/27453.trsp
/usr/share/gpredict/data/trsp/27607.trsp
/usr/share/gpredict/data/trsp/27844.trsp
/usr/share/gpredict/data/trsp/27848.trsp
/usr/share/gpredict/data/trsp/27939.trsp
/usr/share/gpredict/data/trsp/28375.trsp
/usr/share/gpredict/data/trsp/28650.trsp
/usr/share/gpredict/data/trsp/28654.trsp
/usr/share/gpredict/data/trsp/28895.trsp
/usr/share/gpredict/data/trsp/32785.trsp
/usr/share/gpredict/data/trsp/32787.trsp
/usr/share/gpredict/data/trsp/32789.trsp
/usr/share/gpredict/data/trsp/32791.trsp
/usr/share/gpredict/data/trsp/33493.trsp
/usr/share/gpredict/data/trsp/33498.trsp
/usr/share/gpredict/data/trsp/33499.trsp
/usr/share/gpredict/data/trsp/33591.trsp
/usr/share/gpredict/data/trsp/35865.trsp
/usr/share/gpredict/data/trsp/35870.trsp
/usr/share/gpredict/data/trsp/35932.trsp
/usr/share/gpredict/data/trsp/35933.trsp
/usr/share/gpredict/data/trsp/35934.trsp
/usr/share/gpredict/data/trsp/35935.trsp
/usr/share/gpredict/data/trsp/36122.trsp
/usr/share/gpredict/data/trsp/7530.trsp
/usr/share/pixmaps/gpredict-icon.png
/usr/share/pixmaps/gpredict/icons/gpredict-antenna-small.png
/usr/share/pixmaps/gpredict/icons/gpredict-antenna.png
/usr/share/pixmaps/gpredict/icons/gpredict-azel-small.png
/usr/share/pixmaps/gpredict/icons/gpredict-calendar.png
/usr/share/pixmaps/gpredict/icons/gpredict-clock-small.png
/usr/share/pixmaps/gpredict/icons/gpredict-clock.png
/usr/share/pixmaps/gpredict/icons/gpredict-crash.png
/usr/share/pixmaps/gpredict/icons/gpredict-icon.png
/usr/share/pixmaps/gpredict/icons/gpredict-layout-00.png
/usr/share/pixmaps/gpredict/icons/gpredict-layout-01.png
/usr/share/pixmaps/gpredict/icons/gpredict-layout-02.png
/usr/share/pixmaps/gpredict/icons/gpredict-layout-03.png
/usr/share/pixmaps/gpredict/icons/gpredict-layout-04.png
/usr/share/pixmaps/gpredict/icons/gpredict-layout-05.png
/usr/share/pixmaps/gpredict/icons/gpredict-layout-06.png
/usr/share/pixmaps/gpredict/icons/gpredict-layout-07.png
/usr/share/pixmaps/gpredict/icons/gpredict-layout-08.png
/usr/share/pixmaps/gpredict/icons/gpredict-layout-99.png
/usr/share/pixmaps/gpredict/icons/gpredict-leds.png
/usr/share/pixmaps/gpredict/icons/gpredict-mod-attach.png
/usr/share/pixmaps/gpredict/icons/gpredict-mod-close.png
/usr/share/pixmaps/gpredict/icons/gpredict-mod-config.png
/usr/share/pixmaps/gpredict/icons/gpredict-mod-detach.png
/usr/share/pixmaps/gpredict/icons/gpredict-mod-popup.png
/usr/share/pixmaps/gpredict/icons/gpredict-notebook.png
/usr/share/pixmaps/gpredict/icons/gpredict-oscilloscope-small.png
/usr/share/pixmaps/gpredict/icons/gpredict-oscilloscope.png
/usr/share/pixmaps/gpredict/icons/gpredict-planner-small.png
/usr/share/pixmaps/gpredict/icons/gpredict-planner.png
/usr/share/pixmaps/gpredict/icons/gpredict-polar-small.png
/usr/share/pixmaps/gpredict/icons/gpredict-sat-list.png
/usr/share/pixmaps/gpredict/icons/gpredict-sat-pref.png
/usr/share/pixmaps/gpredict/icons/gpredict-shuttle-small.png
/usr/share/pixmaps/gpredict/icons/gpredict-shuttle.png
/usr/share/pixmaps/gpredict/maps/earth_800.png
/usr/share/pixmaps/gpredict/maps/nasa-bmng-01_1024.jpg
/usr/share/pixmaps/gpredict/maps/nasa-bmng-01_2048.jpg
/usr/share/pixmaps/gpredict/maps/nasa-bmng-03_1024.jpg
/usr/share/pixmaps/gpredict/maps/nasa-bmng-03_2048.jpg
/usr/share/pixmaps/gpredict/maps/nasa-bmng-05_1024.jpg
/usr/share/pixmaps/gpredict/maps/nasa-bmng-05_2048.jpg
/usr/share/pixmaps/gpredict/maps/nasa-bmng-07_1024.jpg
/usr/share/pixmaps/gpredict/maps/nasa-bmng-07_2048.jpg
/usr/share/pixmaps/gpredict/maps/nasa-bmng-08_1024.jpg
/usr/share/pixmaps/gpredict/maps/nasa-bmng-08_2048.jpg
/usr/share/pixmaps/gpredict/maps/nasa-topo_1024.jpg
/usr/share/pixmaps/gpredict/maps/nasa-topo_1600.jpg
/usr/share/pixmaps/gpredict/maps/nasa-topo_2048.jpg
/usr/share/pixmaps/gpredict/maps/nasa-topo_800.png

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*

%files locales -f gpredict.lang
%defattr(-,root,root,-)

